name: esds-funnel-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - catalogue
  - dask
  - fsspec
  - joblib
  - netcdf4
  - pip
  - pooch
  - prefect>=0.15.9,<2.0
  - pydantic
  - pytest
  - pytest-cov
  - pytest-sugar
  - pytest-xdist
  - xarray
  - zarr
  - pip:
      - -r ../requirements.txt
