name: esds-funnel-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - catalogue
  - dask
  - fsspec
  - intake-esm
  - joblib
  - netcdf4
  - pip
  - pooch
  - prefect>=0.15.9,<2.0
  - pydantic
  - pytest
  - pytest-cov
  - pytest-sugar
  - pytest-xdist
  - s3fs
  - sqlalchemy-utils
  - sqlalchemy>=1.4.21
  - xarray
  - zarr
  - pip:
      - -r ../requirements.txt
      - git+https://github.com/NCAR/xcollection
