name: esds-funnel-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - catalogue
  - dask
  - intake-esm
  - netcdf4
  - pydantic
  - pytest
  - pytest-cov
  - pytest-sugar
  - pytest-xdist
  - xarray
  - zarr
